lang        : "en"
logo: /assets/img/logo.png
title       : Old Maid Card Game
description : LAMAS project by Group 2.
author      : Ömer Tarik Özyilmaz, Andreea Tudor, Nora Majeris
theme       : minima

# Include/Exclude filetypes
include:
  - _pages

header_pages:
  - /pages/game.md
  - /pages/model.md
  - /pages/results.md
  - /pages/references.md