lang        : "en"
logo        : /assets/img/logo.png
title       : Old Maid Logic Project
author      : Andreea, Nora, and Ömer
theme       : minima
minima:
  skin : dark

header_pages:
  - game.md
  - model.md
  - results.md
  - discussion.md
  - references.md